name: publish-and-release

on:
  push:
    branches:
      - master
    tags:
      - "**" # TODO: improve this match or use semver validation

jobs:
  # main.yml is ignored when pushing tags (aka, publish-releasing).
  # Then, it is called here to assure pipeline consistency.
  main-ci:
    name: Main CI
    uses: ./.github/workflows/main.yml
    secrets: inherit

  build-and-test-dist:
    name: Build and Test distribution
    runs-on: ubuntu-latest
    needs: main-ci
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4

      - name: Prepare build environemnt
        run: |
          chmod +x .github/scripts/dist-health-check.sh
          pip install --user python-minifier wheel setuptools

      - name: Build distribution
        run: make dist

      - name: Check dist health
        run: .github/scripts/dist-health-check.sh

      - name: Save dist files
        uses: actions/upload-artifact@v3
        with:
          name: dist-folder
          path: dist

  pypi-publish:
    name: Upload release to PyPI
    needs: build-and-test-dist
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/dynaconf
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Get distribution
        uses: actions/download-artifact@v3
        with:
          name: dist-folder
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: Create GitHub Release
    needs: pypi-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4

    - name: Install git-changelog
      run: pip install git-changelog

    - name: Prepare release notes
      run: |
        git-changelog --release-notes > release-notes.md
        echo "Release notes being used:"
        cat release-notes.md

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        body_path: release-notes.md

  # https://github.com/marketplace/actions/netlify-actions
  netlify-publish:
    name: Publish documentation to Netlify
    runs-on: ubuntu-latest
    needs: pypi-publish
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: echo "TODO add Netlify tokens here"

      # - name: Build docs
      #   run: |
      #     pip install --user -r requirements_dev.txt
      #     make docs

      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v2.0
      #   with:
      #     publish-dir: './site'
      #     production-branch: master
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     deploy-message: "Deploy from GitHub Actions"
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   timeout-minutes: 1
